import {TEX_CAMERA} from '../../library/jslibm/PatternTextures.js';

export const Textures = {
    //
    // list of texures to use
    // each texture entry has is array object {name:diplay_name, path:path} 
    // name is optional, if missing it will be constructed from path 
    //
    t1:[
      {name:'momath1',path:'../library/images/momathbw2.png'},
      {name:'momath2',path:'../library/images/momathbw1.png'},
      {name:'web cam',path:'[camera]'},     
      {name:'coil',path:'../library/images/acoil.png'},
      {name:'coil2',path:'../library/images/acoil2.png'},
      {name:'temp',path:'../library/images/temp.png'},
      {name:'temp2',path:'../library/images/temp2.png'},
      {name:'leaf',path:'../library/images/leaf.png'},
      {name:'alligator',path:'../library/images/alligator900.png'},
      {name:'another leaf',path:'../library/images/leaf500.png'},
      {name:'leafswirl',path:'../library/images/leafwhirl.png'},
      {name:'leafwhirl',path:'../library/images/leafwhirl2.png'},
      {name:'flashlight',path:'../library/images/blackflash.png'},
      {name:'redbudlong',path:'../library/images/redbud_longstem.png'},
      {name:'redbudshort',path:'../library/images/redbud_shortstem.png'},
      {name:'hand',path:'../library/images/mano.png'},
      {name:'shell',path:'../library/images/shell.png'},
      {name:'duck',path:'../library/images/duck.png'},
      {name:'boat',path:'../library/images/boat.png'},
      {name:'boat2',path:'../library/images/boat2.png'},
      {name:'line1',path:'../library/images/line1.png'},
      {name:'line2',path:'../library/images/line2.png'},
      {name:'line3',path:'../library/images/line3.png'}],
    t2:[
      {name:'temp',path:'../library/images/temp.png'},
      {name:'leaf',path:'../library/images/leaf.png'},
      {name:'alligator',path:'../library/images/alligator900.png'},
      {name:'another leaf',path:'../library/images/leaf500.png'},
      {name:'leafswirl',path:'../library/images/leafwhirl.png'},
      {name:'leafwhirl',path:'../library/images/leafwhirl2.png'},
      {name:'flashlight',path:'../library/images/blackflash.png'},
      {name:'redbudlong',path:'../library/images/redbud_longstem.png'},
      {name:'redbudshort',path:'../library/images/redbud_shortstem.png'},
      {name:'hand',path:'../library/images/mano.png'},
      {name:'shell',path:'../library/images/shell.png'},
      {name:'duck',path:'../library/images/duck.png'},
      {name:'boat',path:'../library/images/boat.png'},
      {name:'boat2',path:'../library/images/boat2.png'},
      {name:'line1',path:'../library/images/line1.png'},
      {name:'line2',path:'../library/images/line2.png'},
      {name:'line3',path:'../library/images/line3.png'},
      {name:'haeckel 01',path:'../library/images/haeckel/haeckel_01.png'},
      {name:'haeckel 02',path:'../library/images/haeckel/haeckel_02.png'},
      {name:'haeckel 03',path:'../library/images/haeckel/haeckel_03.png'},
      {name:'haeckel 04',path:'../library/images/haeckel/haeckel_04.png'},
      {name:'haeckel 05',path:'../library/images/haeckel/haeckel_05.png'},
      {name:'haeckel 06',path:'../library/images/haeckel/haeckel_06.png'},
      {name:'haeckel 07',path:'../library/images/haeckel/haeckel_07.png'},
      {name:'haeckel 08',path:'../library/images/haeckel/haeckel_08.png'},
      {name:'haeckel 09',path:'../library/images/haeckel/haeckel_09.png'},
      {name:'haeckel 10',path:'../library/images/haeckel/haeckel_10.png'},
      {name:'haeckel 11',path:'../library/images/haeckel/haeckel_11.png'},
      {name:'haeckel 12',path:'../library/images/haeckel/haeckel_12.png'},
      {name:'haeckel 13',path:'../library/images/haeckel/haeckel_13.png'},
      {name:'haeckel 14',path:'../library/images/haeckel/haeckel_14.png'},
      {name:'haeckel 15',path:'../library/images/haeckel/haeckel_15.png'},
      {name:'haeckel 16',path:'../library/images/haeckel/haeckel_16.png'},
      {name:'haeckel 17',path:'../library/images/haeckel/haeckel_17.png'},
      {name:'haeckel 18',path:'../library/images/haeckel/haeckel_18.png'},
      /*{name:'haeckel 19',path:'../library/images/haeckel/haeckel_19.png'},
      {name:'haeckel 20',path:'../library/images/haeckel/haeckel_20.png'},
      {name:'haeckel 21',path:'../library/images/haeckel/haeckel_21.png'},
      {name:'haeckel 22',path:'../library/images/haeckel/haeckel_22.png'},
      {name:'haeckel 23',path:'../library/images/haeckel/haeckel_23.png'},
      {name:'haeckel 24',path:'../library/images/haeckel/haeckel_24.png'},
      {name:'haeckel 25',path:'../library/images/haeckel/haeckel_25.png'},
      {name:'haeckel 26',path:'../library/images/haeckel/haeckel_26.png'},
      {name:'haeckel 27',path:'../library/images/haeckel/haeckel_27.png'},
      {name:'haeckel 28',path:'../library/images/haeckel/haeckel_28.png'},
      {name:'haeckel 29',path:'../library/images/haeckel/haeckel_29.png'},
      {name:'video 1', path:'../library/video/horo_lambert_333_01.mp4'},
      {name:'video 2', path:'../library/video/horo_lambert_433_01b.mp4'},      
      {name:'video 3', path:'../library/video/horo_lambert_433_01d.mp4'},      
      {name:'video 4', path:'../library/video/horo_lambert_433_01f.mp4'},      
      {name:'video 5', path:'../library/video/horo_tetra_07a.mp4'},      
      {name:'video 6', path:'../library/video/horo_tetra_07b.mp4'},  
      {name:'video 7', path:'../library/video/horo_tetra_07h.webm'}, */ 
    ]
}

Textures.all = Textures.t1
