@echo off
rem make_scripts.bat -- generate scripts.js from a directory of .js files
rem Usage: make_scripts.bat <scripts_dir> <output_file>
rem Example (from js/): make_scripts.bat ..\scripts scripts.js

setlocal enabledelayedexpansion

set "SCRIPTS_DIR=%~1"
set "OUTPUT=%~2"

rem Write file header (> creates/overwrites the file)
echo // scripts.js -- auto-generated by make_scripts.bat> "%OUTPUT%"
echo // One filename per line; consumed by makeScriptsArray() in JS.>> "%OUTPUT%"
echo export const scripts=`>> "%OUTPUT%"

rem Append one filename per .js file found in SCRIPTS_DIR
for %%f in ("%SCRIPTS_DIR%\*.js") do (
    echo %%~nxf>> "%OUTPUT%"
)

echo `; >> "%OUTPUT%"

echo Generated %OUTPUT%
endlocal
