rem 
rem call make_preset ..\presets\wp\*.json presets_wp.js
rem call make_preset ..\presets\klm\*.json presets_klm.js
rem call make_preset ..\presets\klmn\*.json presets_klmn.js
rem call make_preset ..\presets\5splanes\*.json presets_5splanes.js
rem call make_preset ..\presets\frieze\*.json presets_frieze.js
rem call make_preset ..\presets\spherical\*.json presets_spherical.js
rem call make_preset ..\presets\klx\*.json presets_klx.js
rem call make_preset ..\presets\imageArray\*.json presets_imageArray.js
rem 
call make_preset ..\presets\color\*.json presets_color.js
rem call make_preset ..\presets\orbifold\*.json presets_orbifold.js

rem ── Generate scripts.js from ../scripts/*.js ──────────────────────────────
call :make_scripts ..\scripts scripts.js

pause
goto :eof

:make_scripts
setlocal enabledelayedexpansion
set SCRIPTS_DIR=%~1
set OUTPUT=%~2
(
    echo // scripts.js -- auto-generated by make_presets.bat
    echo // Lists all animation scripts in the scripts/ folder.
    echo export const scripts = [
    for %%f in (%SCRIPTS_DIR%\*.js) do (
        set "fname=%%~nf"
        echo     { name: '!fname!', url: './scripts/%%~nxf' },
    )
    echo ];
) > %OUTPUT%
echo Generated %OUTPUT%
endlocal
goto :eof
