// scripts.js — auto-generated by make_presets.bat
// Lists all animation scripts in the scripts/ folder.
// Each entry: { name: string, url: string (relative to the app's HTML page) }

export const scripts = [
    { name: 'circular_motion', url: './scripts/circular_motion.js' },
    { name: 'linear_motion',   url: './scripts/linear_motion.js'   },
];
